### ISSUE TITLE
Very slow addition of reactions.

### ISSUE THREAD

**Issue by SunnyElite** [BundledSticksInkorperated/Discore#29] opened 2017-09-23 06:46 UTC
Hi, today I started bot, and it started to add reactions very slowly, although yesterday everything was fine, I did not touch anything in the code. What could be the reason?

**Comment by teh-random-name** [comment] 2017-09-23 22:15
There could be millions of reasons as to why its not working, but it would make it just the bit easier if you were to give some context, etc code.

**Comment by SunnyElite** [comment] 2017-09-24 01:06
`var Message = Client.GetChannelMessage(0, 0).GetAwaiter().GetResult();

await Message.CreateReaction(new DiscordReactionEmoji("null", 0);

await Message.CreateReaction(new DiscordReactionEmoji("null", 0);`

Actually it worked perfectly before, now it does not.

**Comment by SunnyElite** [comment] 2017-09-24 01:12
Also very slow reaction to the pressed reaction - `OnMessageReactionAdded`
Sometimes it takes 10 seconds for `OnMessageReactionAdded` to show that the response was clicked.

**Comment by Francessco121** [comment] 2017-09-24 02:38
Well, the first problem *could* be that your running `GetChannelMessage` synchronously.

However, I'm willing to bet you're hitting rate-limits. `GetChannelMessage` has a pretty low rate-limit, I'm not sure about reactions though.

As for `OnMessageReactionAdded` being delayed, I can look further into that.

What I recommend is that you use `DiscordHttpClient` to add reactions by message IDs, so you don't need to get the full message object.

**Comment by SunnyElite** [comment] 2017-09-24 02:53
`OnMessageReactionAdded` As it turned out works fine, the problem is only in the reactions.

**Comment by SunnyElite** [comment] 2017-09-24 02:57
Also, if I press the reaction for the first time, it works without delay, and all subsequent ones with a delay.

**Comment by SunnyElite** [comment] 2017-09-24 03:00
And the code itself is executed quickly, as before, but there is a feeling that the discord itself adds them with a delay.

**Comment by Francessco121** [comment] 2017-09-24 03:18
> Also, if I press the reaction for the first time, it works without delay, and all subsequent ones with a delay.

That sounds exactly like rate-limits kicking in. Discore automatically waits if the request hits a rate limit, causing something like `AddReaction` to take a little bit longer occasionally.

> And the code itself is executed quickly, as before, but there is a feeling that the discord itself adds them with a delay.

That may be just lag on your end, a bug in the client, or potentially the bot having a delayed connection to Discord in general.

-------------------

I have a feeling this is working as intended, but I'll take a good look at the reaction code and try it myself tomorrow.

**Comment by SunnyElite** [comment] 2017-09-24 03:32
Well thank you.
Just 2 - 3 days ago this code worked perfectly and quickly.

**Comment by Francessco121** [comment] 2017-09-24 05:38
The rate-limits aren't static, they could have changed recently. Not likely, but possibly.

**Comment by SunnyElite** [comment] 2017-09-24 08:47
Most likely, because everything else works quickly.

**Comment by SunnyElite** [comment] 2017-09-24 08:50
As there will be an opportunity, look please, as you have, so whether slowly?

**Comment by Francessco121** [comment] 2017-09-24 19:14
So after doing some testing myself, using the code you provided (getting a message, then adding 2 reactions), the only thing slowing down the adding each emoji is rate-limits. A bot is only allowed to add a reaction in a channel once per the reset time (which is actually decently small). What I saw was that the second reaction would always take longer (especially if there were a lot of messages to add reactions too), because of how often I was hitting the rate-limit. Combined with the `GetChannelMessage` call, and I can see exactly why this takes up to 10 seconds occasionally.

The best thing you can do is only add a single reaction, and don't call `GetChannelMessage`. Instead do:
```csharp
await httpClient.CreateReaction(channelId, messageId, new DiscordReactionEmoji(name, id));
```

Calling `CreateReaction` or `AddReaction` twice in a row with no delay will always cause the second call to hit a rate-limit.

**Comment by SunnyElite** [comment] 2017-09-25 06:47
That is, unfortunately, it can not be repaired now? They have there a restriction in the Rate-limit - 1 or what?

httpClient.CreateReaction - I know this, I've already tried a lot. :)

**Comment by Francessco121** [comment] 2017-09-25 12:01
Yes, unfortunately this is a restriction by Discord themselves and there's nothing Discore could change to fix it.

If for some reason you notice all kinds of requests are taking a super long time, then it could be a bug with how Discore handles rate-limits. But from what I saw, it's working as intended still.

**Comment by Francessco121** [comment] 2017-09-26 15:13
Going to close this as "working as intended" for now.

**Closed by Francessco121** 2017-09-26 15:13 UTC
